[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
name = "diesel_struct"
version = "0.1.0"

[dependencies]
quote = "0.3.5"
syn = "0.10.0"

[dev-dependencies]
diesel = "0.8.1"

[lib]
proc-macro = true

[dev-dependencies.diesel_codegen]
version = "0.8"
features = ["sqlite"]
